
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int prentonces = 47;
  public static final int puntoYComa = 7;
  public static final int prIngresar = 27;
  public static final int cor2 = 26;
  public static final int simAsignacion = 6;
  public static final int tigual = 38;
  public static final int cor1 = 25;
  public static final int prfinmetodo = 64;
  public static final int prpara = 55;
  public static final int prsi = 46;
  public static final int coma = 10;
  public static final int prmientras = 43;
  public static final int tpot = 21;
  public static final int prconparametros = 67;
  public static final int tmenorigual = 37;
  public static final int prhasta = 56;
  public static final int BoleanFalso = 9;
  public static final int prfinfuncion = 66;
  public static final int primprimirln = 14;
  public static final int prfuncion = 65;
  public static final int prhastaque = 61;
  public static final int prcon = 58;
  public static final int caracter = 8;
  public static final int tmenor = 35;
  public static final int pror = 40;
  public static final int prdelocontrario = 49;
  public static final int tmayorigual = 36;
  public static final int tmayor = 34;
  public static final int prConValor = 30;
  public static final int pare2 = 24;
  public static final int prnumero = 29;
  public static final int prfinpara = 57;
  public static final int pare1 = 23;
  public static final int EOF = 0;
  public static final int prCadena = 31;
  public static final int prfinmientras = 45;
  public static final int princremental = 59;
  public static final int tdiv = 19;
  public static final int error = 1;
  public static final int BoleanVerdadero = 5;
  public static final int comenta = 16;
  public static final int prBoolean = 33;
  public static final int prfinsegun = 54;
  public static final int trest = 17;
  public static final int prFin = 12;
  public static final int prmetodo = 63;
  public static final int prCaracter = 32;
  public static final int prcomo = 28;
  public static final int prosi = 50;
  public static final int id = 2;
  public static final int tmul = 20;
  public static final int prretornar = 62;
  public static final int tmod = 22;
  public static final int comentarioMulti = 15;
  public static final int prejecutar = 68;
  public static final int prinder = 53;
  public static final int prsegun = 51;
  public static final int prhacer = 44;
  public static final int prInicio = 11;
  public static final int tdiferente = 39;
  public static final int prfinsi = 48;
  public static final int primprimir = 13;
  public static final int prrepetir = 60;
  public static final int prinzq = 52;
  public static final int prnot = 42;
  public static final int prand = 41;
  public static final int digito = 3;
  public static final int tsum = 18;
  public static final int cadena = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "id",
  "digito",
  "cadena",
  "BoleanVerdadero",
  "simAsignacion",
  "puntoYComa",
  "caracter",
  "BoleanFalso",
  "coma",
  "prInicio",
  "prFin",
  "primprimir",
  "primprimirln",
  "comentarioMulti",
  "comenta",
  "trest",
  "tsum",
  "tdiv",
  "tmul",
  "tpot",
  "tmod",
  "pare1",
  "pare2",
  "cor1",
  "cor2",
  "prIngresar",
  "prcomo",
  "prnumero",
  "prConValor",
  "prCadena",
  "prCaracter",
  "prBoolean",
  "tmayor",
  "tmenor",
  "tmayorigual",
  "tmenorigual",
  "tigual",
  "tdiferente",
  "pror",
  "prand",
  "prnot",
  "prmientras",
  "prhacer",
  "prfinmientras",
  "prsi",
  "prentonces",
  "prfinsi",
  "prdelocontrario",
  "prosi",
  "prsegun",
  "prinzq",
  "prinder",
  "prfinsegun",
  "prpara",
  "prhasta",
  "prfinpara",
  "prcon",
  "princremental",
  "prrepetir",
  "prhastaque",
  "prretornar",
  "prmetodo",
  "prfinmetodo",
  "prfuncion",
  "prfinfuncion",
  "prconparametros",
  "prejecutar"
  };
}

